// Référence « Proies et prédateurs » (France). Données de synthèse, modifiables ici.
// zone : absente = France, "nc" = Nouvelle-Calédonie. milieu : "mer"/"douce" (France), "lagon"/"large" (NC). roles : "predateur" et/ou "proie".
// mange : identifiants des poissons-proies. autres : nourriture hors poissons.
window.ESPECES = [
  // ===== Eau douce : prédateurs =====
  {id:"brochet", nom:"Brochet", sci:"Esox lucius", wiki:"Grand_brochet", milieu:"douce", roles:["predateur"], taille:"50–100 cm (jusqu'à 130 cm)",
   habitat:"Eaux calmes, bordures d'herbiers, bras morts, lacs.",
   mange:["gardon","rotengle","ablette","perchette","breme","carassin","chevesne","goujon"],
   autres:"Écrevisses, grenouilles, canetons, petits rongeurs ; cannibale.",
   conseil:"Avale des proies jusqu'à la moitié de sa taille : leurres de 10 à 25 cm."},
  {id:"sandre", nom:"Sandre", sci:"Sander lucioperca", wiki:"Sandre", milieu:"douce", roles:["predateur"], taille:"40–80 cm (jusqu'à 100 cm)",
   habitat:"Fonds durs, eaux un peu troubles, grands fleuves, lacs et canaux.",
   mange:["ablette","goujon","gardon","perchette","gremille"],
   autres:"Écrevisses.",
   conseil:"Gosier étroit : proies fines et allongées, leurres de 7 à 14 cm."},
  {id:"perche", nom:"Perche", sci:"Perca fluviatilis", wiki:"Perche_commune", milieu:"douce", roles:["predateur"], taille:"20–30 cm (jusqu'à 45 cm)",
   habitat:"Lacs, rivières lentes, structures immergées ; chasse en bandes.",
   mange:["ablette","gardon","vairon","perchette","goujon","gremille"],
   autres:"Écrevisses, larves, vers, crustacés ; cannibale.",
   conseil:"Proies de 3 à 8 cm : petits leurres, cuillers, finesse."},
  {id:"blackbass", nom:"Black-bass", sci:"Micropterus salmoides", wiki:"Achigan_à_grande_bouche", milieu:"douce", roles:["predateur"], taille:"30–50 cm",
   habitat:"Eaux chaudes et calmes, herbiers, bois morts, étangs et lacs.",
   mange:["gardon","ablette","perchette","vairon","rotengle"],
   autres:"Écrevisses, grenouilles, gros insectes.",
   conseil:"Très opportuniste en surface comme au fond."},
  {id:"silure", nom:"Silure", sci:"Silurus glanis", wiki:"Silure_glane", milieu:"douce", roles:["predateur"], taille:"100–200 cm (plus de 2,5 m)",
   habitat:"Grands fleuves et lacs, fosses, bordures encombrées.",
   mange:["breme","carassin","rotengle","chevesne","gardon","hotu"],
   autres:"Écrevisses, amphibiens, oiseaux d'eau, mollusques (corbicules).",
   conseil:"Gros leurres souples et vibrants, souvent près du fond."},
  {id:"truite", nom:"Truite fario", sci:"Salmo trutta", wiki:"Truite_fario", milieu:"douce", roles:["predateur"], taille:"20–40 cm (jusqu'à 70 cm)",
   habitat:"Eaux vives, fraîches et oxygénées, torrents et rivières.",
   mange:["vairon","chabot","loche","goujon"],
   autres:"Insectes aquatiques et terrestres, gammares ; les grosses truites deviennent piscivores.",
   conseil:"Imitations de vairon de 3 à 7 cm, cuillers tournantes."},
  {id:"chevesne", nom:"Chevesne", sci:"Squalius cephalus", wiki:"Chevesne", milieu:"douce", roles:["predateur","proie"], taille:"30–50 cm",
   habitat:"Rivières courantes, sous les arbres en bordure.",
   mange:["vairon","ablette","goujon"],
   autres:"Insectes, fruits tombés, écrevisses, graines.",
   robe:"Dos gris-vert sombre, flancs argentés à reflets dorés, écailles bordées de noir, nageoires ventrales orangées.",
   conseil:"Omnivore : petits poissons nageurs, insectes de surface."},
  // ===== Eau douce : poissons fourrage =====
  {id:"gardon", nom:"Gardon", sci:"Rutilus rutilus", wiki:"Gardon", milieu:"douce", roles:["proie"], taille:"10–25 cm",
   habitat:"Eaux calmes ou lentes, en bancs.", robe:"Dos vert-bleuté, flancs très argentés, nageoires rouge orangé, œil rouge."},
  {id:"ablette", nom:"Ablette", sci:"Alburnus alburnus", wiki:"Ablette", milieu:"douce", roles:["proie"], taille:"10–15 cm",
   habitat:"Pleine eau et surface, gros bancs.", robe:"Corps fin très brillant, argent miroir, dos vert-bleu, ventre blanc."},
  {id:"rotengle", nom:"Rotengle", sci:"Scardinius erythrophthalmus", wiki:"Rotengle", milieu:"douce", roles:["proie"], taille:"15–30 cm",
   habitat:"Eaux calmes riches en herbiers.", robe:"Flancs dorés à bronze, nageoires rouge vif, dos brun-vert."},
  {id:"goujon", nom:"Goujon", sci:"Gobio gobio", wiki:"Goujon", milieu:"douce", roles:["proie"], taille:"8–15 cm",
   habitat:"Fond de sable ou de gravier, en petits groupes.", robe:"Brun-gris tacheté de sombre le long du flanc, ventre clair, 2 barbillons."},
  {id:"vairon", nom:"Vairon", sci:"Phoxinus phoxinus", wiki:"Vairon", milieu:"douce", roles:["proie"], taille:"5–10 cm",
   habitat:"Eaux vives et fraîches, en bancs près des bords.", robe:"Vert olive marbré de taches sombres, flanc doré, ventre rouge chez le mâle au printemps."},
  {id:"breme", nom:"Brème (jeune)", sci:"Abramis brama", wiki:"Brème_commune", milieu:"douce", roles:["proie"], taille:"Juvéniles 10–25 cm (adulte 30–60 cm)",
   habitat:"Eaux lentes et profondes, fonds vaseux.", robe:"Corps haut et plat, argenté chez le jeune, bronze chez l'adulte."},
  {id:"carassin", nom:"Carassin", sci:"Carassius carassius", wiki:"Carassin_commun", milieu:"douce", roles:["proie"], taille:"15–30 cm",
   habitat:"Étangs et eaux calmes envasées.", robe:"Bronze doré, corps haut, sans barbillons."},
  {id:"chabot", nom:"Chabot", sci:"Cottus gobio", wiki:"Chabot_commun", milieu:"douce", roles:["proie"], taille:"8–15 cm",
   habitat:"Sous les pierres des rivières fraîches.", robe:"Brun marbré, grosse tête aplatie, larges nageoires pectorales."},
  {id:"loche", nom:"Loche franche", sci:"Barbatula barbatula", wiki:"Loche_franche", milieu:"douce", roles:["proie"], taille:"8–12 cm",
   habitat:"Fond de graviers en eau courante.", robe:"Corps allongé brun-jaune marbré, 6 barbillons."},
  {id:"hotu", nom:"Hotu", sci:"Chondrostoma nasus", wiki:"Hotu", milieu:"douce", roles:["proie"], taille:"25–40 cm",
   habitat:"Grandes rivières courantes, fonds de graviers, en bancs.", robe:"Argenté, dos gris-vert, nageoires inférieures rougeâtres, bouche sous le museau."},
  {id:"gremille", nom:"Grémille", sci:"Gymnocephalus cernua", wiki:"Grémille", milieu:"douce", roles:["proie"], taille:"10–15 cm",
   habitat:"Fonds de fleuves et de lacs.", robe:"Brun-jaune tacheté de noir, dorsale épineuse ponctuée."},
  {id:"perchette", nom:"Perchette", sci:"Perca fluviatilis", wiki:"Perche_commune", milieu:"douce", roles:["proie"], taille:"5–15 cm",
   habitat:"Bordures, structures, en bancs.", robe:"Vert-jaune à 5–7 bandes verticales sombres, nageoires ventrales orange vif."},

  // ===== Mer : prédateurs =====
  {id:"bar", nom:"Bar (loup)", sci:"Dicentrarchus labrax", wiki:"Bar_commun", milieu:"mer", roles:["predateur"], taille:"40–60 cm (jusqu'à 1 m)",
   habitat:"Côtes, estuaires, zones d'écume, roches et plages ; Atlantique, Manche, Méditerranée.",
   mange:["sardine","anchois","sprat","lancon","atherine","chinchard","mulet","gobie","tacaud"],
   autres:"Crabes, crevettes, seiches et calmars, vers polychètes.",
   conseil:"Leurres de 9 à 15 cm imitant lançon, sardine ou mulet."},
  {id:"lieu", nom:"Lieu jaune", sci:"Pollachius pollachius", wiki:"Lieu_jaune", milieu:"mer", roles:["predateur"], taille:"40–80 cm (jusqu'à 1,3 m)",
   habitat:"Roches, laminaires, épaves, de 1 à 100 m ; Atlantique et Manche.",
   mange:["lancon","sprat","tacaud","chinchard","sardine","atherine"],
   autres:"Calmars, crevettes.",
   conseil:"Souples de 10 à 18 cm type lançon, près des épaves."},
  {id:"maquereau", nom:"Maquereau", sci:"Scomber scombrus", wiki:"Maquereau_commun", milieu:"mer", roles:["predateur","proie"], taille:"25–40 cm",
   habitat:"Pleine eau côtière, en bancs ; présent en été près des côtes.",
   mange:["sprat","anchois","sardine","lancon","atherine"],
   autres:"Zooplancton : copépodes, krill, larves.",
   robe:"Dos vert-bleu zébré de bandes noires ondulées, ventre blanc nacré.",
   conseil:"Petits leurres brillants de 3 à 8 cm, mitraillettes."},
  {id:"thon", nom:"Thon rouge", sci:"Thunnus thynnus", wiki:"Thon_rouge_de_l'Atlantique", milieu:"mer", roles:["predateur"], taille:"100–250 cm",
   habitat:"Large ; golfe de Gascogne en été-automne, Méditerranée.",
   mange:["sardine","anchois","maquereau","chinchard","sprat","orphie"],
   autres:"Calmars, crustacés pélagiques.",
   conseil:"Stickbaits et poppers de 15 à 25 cm, sardine ou maquereau."},
  {id:"bonite", nom:"Bonite à dos rayé", sci:"Sarda sarda", wiki:"Bonite_à_dos_rayé", milieu:"mer", roles:["predateur"], taille:"40–70 cm",
   habitat:"Pleine eau, chasses en surface ; Méditerranée et Atlantique sud.",
   mange:["sardine","anchois","atherine","sprat","maquereau"],
   autres:"Calmars.",
   conseil:"Jigs et casting jigs de 20 à 40 g, lancés vite."},
  {id:"seriole", nom:"Sériole", sci:"Seriola dumerili", wiki:"Sériole_couronnée", milieu:"mer", roles:["predateur"], taille:"60–120 cm (jusqu'à 1,9 m)",
   habitat:"Tombants, épaves, hauts-fonds ; Méditerranée surtout.",
   mange:["chinchard","maquereau","sardine","mulet","orphie"],
   autres:"Calmars, seiches.",
   conseil:"Jigs lourds et gros stickbaits."},
  {id:"dorade", nom:"Dorade royale", sci:"Sparus aurata", wiki:"Dorade_royale", milieu:"mer", roles:["predateur"], taille:"30–50 cm (jusqu'à 70 cm)",
   habitat:"Fonds sableux et rocheux côtiers, lagunes, estuaires.",
   mange:[],
   autres:"Surtout coquillages et crustacés : moules, crabes, bernard-l'ermite, crevettes, oursins, vers. Peu de poissons.",
   conseil:"Peu réceptive aux leurres imitant des poissons : imitations de crabe et petits leurres de fond."},
  // ===== Mer : poissons fourrage =====
  {id:"sardine", nom:"Sardine", sci:"Sardina pilchardus", wiki:"Sardine_commune", milieu:"mer", roles:["proie"], taille:"15–25 cm",
   habitat:"Pleine eau côtière, gros bancs.", robe:"Dos bleu-vert, flancs argentés, ligne de taches sombres sur le haut du flanc."},
  {id:"anchois", nom:"Anchois", sci:"Engraulis encrasicolus", wiki:"Anchois_commun", milieu:"mer", roles:["proie"], taille:"10–15 cm",
   habitat:"Pleine eau, bancs très denses.", robe:"Corps fin semi-translucide, dos bleu-vert, bande latérale argentée."},
  {id:"sprat", nom:"Sprat", sci:"Sprattus sprattus", wiki:"Sprat", milieu:"mer", roles:["proie"], taille:"8–14 cm",
   habitat:"Côtes et estuaires, en bancs.", robe:"Argenté, dos bleu-vert, ventre caréné."},
  {id:"lancon", nom:"Lançon (équille)", sci:"Ammodytes tobianus", wiki:"Lançon_équille", milieu:"mer", roles:["proie"], taille:"10–20 cm",
   habitat:"Fonds de sable où il s'enfouit, en bancs près des plages.", robe:"Très effilé, argent brillant, dos vert-bleu."},
  {id:"chinchard", nom:"Chinchard", sci:"Trachurus trachurus", wiki:"Chinchard_commun", milieu:"mer", roles:["proie"], taille:"Juvéniles 10–25 cm",
   habitat:"Pleine eau, bancs, près des roches et des ports.", robe:"Dos gris-vert, flancs argentés, ligne latérale à scutelles, tache noire sur l'opercule."},
  {id:"atherine", nom:"Athérine (prêtre)", sci:"Atherina presbyter", wiki:"Atherina_presbyter", milieu:"mer", roles:["proie"], taille:"7–15 cm",
   habitat:"Ports, plages, estuaires, en bancs.", robe:"Translucide, large bande argentée brillante sur le flanc."},
  {id:"orphie", nom:"Orphie", sci:"Belone belone", wiki:"Orphie", milieu:"mer", roles:["proie"], taille:"40–80 cm",
   habitat:"Surface, côtes au printemps.", robe:"Très effilée, dos vert-bleu, flancs argentés, long bec, arêtes vertes."},
  {id:"tacaud", nom:"Tacaud", sci:"Trisopterus luscus", wiki:"Tacaud_commun", milieu:"mer", roles:["proie"], taille:"15–30 cm",
   habitat:"Roches, épaves, en bancs.", robe:"Cuivré à 4–5 bandes verticales sombres, petit barbillon au menton."},
  {id:"mulet", nom:"Mulet (jeune)", sci:"Chelon labrosus", wiki:"Mulet_lippu", milieu:"mer", roles:["proie"], taille:"Juvéniles 5–20 cm",
   habitat:"Ports, estuaires, surface, en bancs.", robe:"Gris argenté, fines lignes sombres longitudinales."},
  {id:"gobie", nom:"Gobie", sci:"Gobius paganellus", wiki:"Gobie_paganel", milieu:"mer", roles:["proie"], taille:"8–12 cm",
   habitat:"Fonds rocheux et flaques de l'estran.", robe:"Brun marbré, bande claire au bord de la première dorsale."},
  // ======================= NOUVELLE-CALÉDONIE (zone "nc") =======================
  // milieu : "lagon" (lagon, récif, passes, mangrove) ou "large" (hors récif, hauturier)
  // ===== Lagon et récif : prédateurs =====
  {id:"nc-gt", zone:"nc", nom:"Carangue à grosse tête (GT)", sci:"Caranx ignobilis", wiki:"Caranx_ignobilis", milieu:"lagon", roles:["predateur"], taille:"60–120 cm (jusqu'à 1,7 m, 60 kg)",
   habitat:"Passes, tombants du récif, platiers à marée montante, embouchures.",
   mange:["nc-fusilier","nc-mulet","nc-selar","nc-rouget","nc-balaou","nc-sardine"],
   autres:"Poulpes, langoustes et crabes ; opportuniste, attaque parfois des oiseaux.",
   conseil:"Poppers et stickbaits de 15 à 25 cm, triples ou simples renforcés."},
  {id:"nc-carangue-bleue", zone:"nc", nom:"Carangue bleue", sci:"Caranx melampygus", wiki:"Caranx_melampygus", milieu:"lagon", roles:["predateur"], taille:"40–70 cm (jusqu'à 1 m)",
   habitat:"Récifs, platiers, passes, chasse en petits groupes.",
   mange:["nc-sardine","nc-anchois","nc-balaou","nc-fusilier","nc-rouget"],
   autres:"Crevettes et petits crustacés.",
   conseil:"Stickbaits et jigs de 9 à 15 cm, récupération rapide."},
  {id:"nc-saumonee", zone:"nc", nom:"Saumonée (loche saumonée)", sci:"Plectropomus leopardus", wiki:"Plectropomus_leopardus", milieu:"lagon", roles:["predateur"], taille:"40–60 cm (jusqu'à 1 m)",
   habitat:"Récifs coralliens, patates, tombants du lagon.",
   mange:["nc-fusilier","nc-rouget","nc-selar","nc-sardine"],
   autres:"Calmars, crevettes.",
   conseil:"Poissons nageurs plongeants et jigs près des patates."},
  {id:"nc-bec-de-cane", zone:"nc", nom:"Bec de cane", sci:"Lethrinus nebulosus", wiki:"Lethrinus_nebulosus", milieu:"lagon", roles:["predateur"], taille:"40–60 cm (jusqu'à 85 cm)",
   habitat:"Fonds sableux et herbiers du lagon, bordure des récifs.",
   mange:[],
   autres:"Surtout crabes, crevettes, mollusques, oursins et vers ; peu de poissons.",
   conseil:"Peu réceptif aux leurres imitant des poissons : leurres de fond type crabe ou crevette."},
  {id:"nc-barracuda", zone:"nc", nom:"Barracuda", sci:"Sphyraena barracuda", wiki:"Sphyraena_barracuda", milieu:"lagon", roles:["predateur"], taille:"60–120 cm (jusqu'à 1,8 m)",
   habitat:"Lagon, passes, bordure des récifs et des mangroves.",
   mange:["nc-mulet","nc-sardine","nc-balaou","nc-selar","nc-fusilier"],
   autres:"Calmars.",
   conseil:"Leurres longs et fins de 15 à 20 cm, bas de ligne acier."},
  {id:"nc-thazard", zone:"nc", nom:"Thazard", sci:"Scomberomorus commerson", wiki:"Scomberomorus_commerson", milieu:"lagon", roles:["predateur"], taille:"70–150 cm (jusqu'à 2,4 m)",
   habitat:"Passes, bordure extérieure du récif, lagon profond.",
   mange:["nc-sardine","nc-anchois","nc-selar","nc-balaou","nc-fusilier"],
   autres:"Calmars.",
   conseil:"Traîne rapide ou casting jigs, bas de ligne acier (dents coupantes)."},
  {id:"nc-lutjan-mangrove", zone:"nc", nom:"Lutjan des mangroves", sci:"Lutjanus argentimaculatus", wiki:"Lutjanus_argentimaculatus", milieu:"lagon", roles:["predateur"], taille:"40–80 cm (jusqu'à 1,2 m)",
   habitat:"Mangroves et embouchures chez le jeune, récifs profonds chez l'adulte.",
   mange:["nc-mulet","nc-sardine","nc-rouget"],
   autres:"Crabes et crevettes.",
   conseil:"Leurres souples et poissons nageurs près des racines et des obstacles."},
  // ===== Large : prédateurs =====
  {id:"nc-dent-de-chien", zone:"nc", nom:"Thon dents de chien", sci:"Gymnosarda unicolor", wiki:"Gymnosarda_unicolor", milieu:"large", roles:["predateur"], taille:"60–120 cm (jusqu'à 2 m)",
   habitat:"Tombants extérieurs du récif et passes, souvent profond.",
   mange:["nc-fusilier","nc-selar","nc-sardine","nc-balaou"],
   autres:"Calmars.",
   conseil:"Jigs lourds et stickbaits plongeants le long des tombants."},
  {id:"nc-thon-jaune", zone:"nc", nom:"Thon jaune", sci:"Thunnus albacares", wiki:"Thunnus_albacares", milieu:"large", roles:["predateur"], taille:"60–150 cm (jusqu'à 2 m)",
   habitat:"Large, sous les chasses d'oiseaux et autour des DCP.",
   mange:["nc-volant","nc-selar","nc-anchois","nc-listao"],
   autres:"Calmars, crustacés pélagiques.",
   conseil:"Stickbaits et poppers de 15 à 25 cm, leurres à jupe en traîne."},
  {id:"nc-wahoo", zone:"nc", nom:"Wahoo", sci:"Acanthocybium solandri", wiki:"Acanthocybium_solandri", milieu:"large", roles:["predateur"], taille:"100–170 cm (jusqu'à 2,5 m)",
   habitat:"Large et bordure extérieure du récif, en solitaire ou petits groupes.",
   mange:["nc-volant","nc-selar","nc-listao","nc-balaou"],
   autres:"Calmars.",
   conseil:"Traîne rapide (12 à 18 nœuds), leurres plongeants, bas de ligne acier."},
  {id:"nc-mahi", zone:"nc", nom:"Mahi-mahi (coryphène)", sci:"Coryphaena hippurus", wiki:"Coryphaena_hippurus", milieu:"large", roles:["predateur"], taille:"60–120 cm (jusqu'à 2 m)",
   habitat:"Large, sous les objets flottants, algues et DCP.",
   mange:["nc-volant","nc-balaou","nc-selar"],
   autres:"Calmars, crustacés pélagiques.",
   conseil:"Leurres à jupe et stickbaits de surface colorés près des objets flottants."},
  {id:"nc-marlin", zone:"nc", nom:"Marlin bleu", sci:"Makaira nigricans", wiki:"Makaira_nigricans", milieu:"large", roles:["predateur"], taille:"200–350 cm",
   habitat:"Grand large, eaux chaudes et profondes.",
   mange:["nc-listao","nc-volant","nc-selar"],
   autres:"Calmars, jeunes thons et coryphènes.",
   conseil:"Gros leurres à jupe de 25 à 35 cm en traîne, hameçons 9/0 à 12/0."},
  // ===== Poissons fourrage =====
  {id:"nc-listao", zone:"nc", nom:"Listao (bonite)", sci:"Katsuwonus pelamis", wiki:"Katsuwonus_pelamis", milieu:"large", roles:["predateur","proie"], taille:"40–80 cm",
   habitat:"Large, gros bancs en surface.", mange:["nc-anchois","nc-sardine","nc-volant"], autres:"Crustacés, calmars.",
   robe:"Dos bleu-violet sombre, ventre argenté marqué de 4 à 6 bandes longitudinales sombres.",
   conseil:"Petits jigs et leurres brillants de 5 à 10 cm ; excellent appât vivant pour le marlin."},
  {id:"nc-sardine", zone:"nc", nom:"Sardine du lagon", sci:"Herklotsichthys quadrimaculatus", wiki:"Herklotsichthys_quadrimaculatus", milieu:"lagon", roles:["proie"], taille:"8–12 cm",
   habitat:"Lagon peu profond, plages et baies, gros bancs.", robe:"Dos bleu-vert, flancs argentés, deux taches jaune-orangé derrière l'opercule."},
  {id:"nc-anchois", zone:"nc", nom:"Anchois tropical", sci:"Stolephorus indicus", wiki:"Stolephorus_indicus", milieu:"lagon", roles:["proie"], taille:"8–15 cm",
   habitat:"Baies et lagon, bancs denses en pleine eau.", robe:"Translucide, large bande latérale argentée, dos légèrement verdâtre."},
  {id:"nc-selar", zone:"nc", nom:"Chinchard à gros yeux (selar)", sci:"Selar crumenophthalmus", wiki:"Selar_crumenophthalmus", milieu:"lagon", roles:["proie"], taille:"15–25 cm",
   habitat:"Lagon, passes et large, bancs souvent la nuit près de la surface.", robe:"Dos bleu-vert métallique, flancs argentés, très gros œil, fine ligne jaune latérale."},
  {id:"nc-mulet", zone:"nc", nom:"Mulet", sci:"Crenimugil crenilabis", wiki:"Crenimugil_crenilabis", milieu:"lagon", roles:["proie"], taille:"20–40 cm",
   habitat:"Platiers, bords de plage, mangroves, en bancs près de la surface.", robe:"Gris argenté, dos olive, tache sombre à la base de la nageoire pectorale."},
  {id:"nc-balaou", zone:"nc", nom:"Balaou (demi-bec)", sci:"Hemiramphus far", wiki:"Hemiramphus_far", milieu:"lagon", roles:["proie"], taille:"20–40 cm",
   habitat:"Surface du lagon et bord du récif.", robe:"Corps fin argenté, dos bleu-vert, 3 à 9 taches sombres sur le flanc, mâchoire inférieure en long bec à pointe rouge."},
  {id:"nc-volant", zone:"nc", nom:"Poisson volant", sci:"Cheilopogon pinnatibarbatus", wiki:"Exocoetidae", milieu:"large", roles:["proie"], taille:"20–40 cm",
   habitat:"Surface du large, plane au-dessus de l'eau pour fuir.", robe:"Dos bleu foncé, ventre argenté, très grandes nageoires pectorales en ailes."},
  {id:"nc-fusilier", zone:"nc", nom:"Fusilier", sci:"Caesio cuning", wiki:"Caesio_cuning", milieu:"lagon", roles:["proie"], taille:"15–30 cm",
   habitat:"Pleine eau le long des récifs et des tombants, gros bancs.", robe:"Dos bleu, arrière du corps et queue jaune vif, ventre blanc-rosé."},
  {id:"nc-rouget", zone:"nc", nom:"Rouget (poisson-chèvre)", sci:"Mulloidichthys flavolineatus", wiki:"Mulloidichthys_flavolineatus", milieu:"lagon", roles:["proie"], taille:"20–35 cm",
   habitat:"Fonds sableux près des récifs, en bancs.", robe:"Blanc argenté, bande jaune longitudinale avec une tache noire, deux barbillons sous le menton."}
];

// ======================= AUTRES PROIES (mollusques, crustacés, vers, insectes…) =======================
// groupe : "Céphalopode", "Crustacé", "Ver", "Insecte", "Amphibien", "Coquillage", "Échinoderme"
window.ESPECES.push(
  // ---- France, mer ----
  {id:"calmar", nom:"Calmar (encornet)", sci:"Loligo vulgaris", wiki:"Calmar_commun", milieu:"mer", groupe:"Céphalopode", roles:["proie"], taille:"15–40 cm (manteau)",
   habitat:"Pleine eau côtière, se rapproche des côtes et des ports la nuit, surtout en automne-hiver.", robe:"Corps fuselé translucide rosé à points pourpres, deux nageoires triangulaires à l'arrière.",
   imitation:"Turluttes, souples type calamar, leurres à jupe."},
  {id:"seiche", nom:"Seiche", sci:"Sepia officinalis", wiki:"Seiche_commune", milieu:"mer", groupe:"Céphalopode", roles:["proie"], taille:"15–30 cm (manteau)",
   habitat:"Fonds sableux et herbiers peu profonds, abondante à la côte au printemps pour pondre.", robe:"Corps ovale aplati, motif zébré brun et blanc qui change en un instant.",
   imitation:"Turluttes et leurres souples larges, couleurs naturelles."},
  {id:"poulpe", nom:"Poulpe", sci:"Octopus vulgaris", wiki:"Pieuvre_commune", milieu:"mer", groupe:"Céphalopode", roles:["proie"], taille:"30–90 cm (bras compris)",
   habitat:"Rochers, cavités et éboulis, de l'estran à 100 m.", robe:"Brun-rouge à beige, peau granuleuse, change de couleur et de texture.",
   imitation:"Leurres souples à tentacules (type octopus), madaï."},
  {id:"crevette-grise", nom:"Crevette grise", sci:"Crangon crangon", wiki:"Crevette_grise", milieu:"mer", groupe:"Crustacé", roles:["proie"], taille:"4–8 cm",
   habitat:"Sable et vase des plages et estuaires, s'enfouit le jour.", robe:"Gris-beige translucide moucheté, se confond avec le sable.",
   imitation:"Petits leurres souples crevette, mouches crevette."},
  {id:"bouquet", nom:"Crevette rose (bouquet)", sci:"Palaemon serratus", wiki:"Palaemon_serratus", milieu:"mer", groupe:"Crustacé", roles:["proie"], taille:"5–10 cm",
   habitat:"Rochers, champs d'algues et flaques, à la côte du printemps à l'automne.", robe:"Translucide strié de fines lignes brun-rouge, rose orangé une fois cuite.",
   imitation:"Leurres souples crevette translucides."},
  {id:"crabe-vert", nom:"Crabe vert (crabe enragé)", sci:"Carcinus maenas", wiki:"Crabe_vert", milieu:"mer", groupe:"Crustacé", roles:["proie"], taille:"5–8 cm (carapace)",
   habitat:"Estran, estuaires, roches et herbiers ; mue au printemps et en été (crabe mou très recherché).", robe:"Vert olive à brun, dessous jaune-orangé chez les vieux mâles.",
   imitation:"Leurres crabe souples, pêche au fond."},
  {id:"etrille", nom:"Étrille", sci:"Necora puber", wiki:"Étrille", milieu:"mer", groupe:"Crustacé", roles:["proie"], taille:"6–9 cm (carapace)",
   habitat:"Rochers et champs de laminaires, de l'estran à 60 m.", robe:"Carapace brun-bleuté veloutée, pattes à rayures bleues, yeux rouges.",
   imitation:"Leurres crabe."},
  {id:"nereis", nom:"Néréis (gravette)", sci:"Hediste diversicolor", wiki:"Hediste_diversicolor", milieu:"mer", groupe:"Ver", roles:["proie"], taille:"6–12 cm",
   habitat:"Vase et sable vaseux des estuaires et des ports.", robe:"Corps segmenté brun-vert à reflets irisés, nombreux petits appendices latéraux.",
   imitation:"Vers souples (type Isome), mouches."},
  {id:"arenicole", nom:"Arénicole (ver de sable)", sci:"Arenicola marina", wiki:"Arénicole", milieu:"mer", groupe:"Ver", roles:["proie"], taille:"12–20 cm",
   habitat:"Sable des plages, signalée par ses tortillons de sable.", robe:"Brun-rouge à noir, gros corps mou avec des branchies rouges.",
   imitation:"Vers souples parfumés, pêche au fond."},
  {id:"moule", nom:"Moule", sci:"Mytilus edulis", wiki:"Moule_commune", milieu:"mer", groupe:"Coquillage", roles:["proie"], taille:"3–8 cm",
   habitat:"Rochers, digues et piquets de l'estran, en colonies.", robe:"Coquille bleu-noir allongée.",
   imitation:"Peu imitable au leurre : appât naturel pour la dorade."},
  // ---- France, eau douce ----
  {id:"ecrevisse", nom:"Écrevisse (américaine, de Louisiane)", sci:"Procambarus clarkii", wiki:"Écrevisse_de_Louisiane", milieu:"douce", groupe:"Crustacé", roles:["proie"], taille:"8–12 cm",
   habitat:"Étangs, canaux et rivières lentes, sous les pierres et dans les berges ; active au crépuscule.", robe:"Rouge sombre à brun, pinces granuleuses rouges (Louisiane) ; brun-vert à taches rouges sur l'abdomen (américaine).",
   imitation:"Leurres souples écrevisse, jigs, crankbaits couleur écrevisse."},
  {id:"gammare", nom:"Gammare (crevette d'eau douce)", sci:"Gammarus pulex", wiki:"Gammarus_pulex", milieu:"douce", groupe:"Crustacé", roles:["proie"], taille:"1–2 cm",
   habitat:"Fond des rivières fraîches, sous les pierres et dans les feuilles.", robe:"Gris-vert translucide, corps arqué.",
   imitation:"Nymphes et mouches gammare."},
  {id:"ephemere", nom:"Éphémère (larve et adulte)", sci:"Ephemera danica", wiki:"Éphémère_(insecte)", milieu:"douce", groupe:"Insecte", roles:["proie"], taille:"1,5–3 cm",
   habitat:"Larves dans le sable et le gravier, éclosions massives en mai-juin à la surface.", robe:"Adulte jaune crème à ailes tachetées, 3 longs filaments caudaux.",
   imitation:"Mouches sèches et nymphes ; petites cuillers pour la truite."},
  {id:"trichoptere", nom:"Trichoptère (porte-bois)", sci:"Trichoptera", wiki:"Trichoptera", milieu:"douce", groupe:"Insecte", roles:["proie"], taille:"1–3 cm",
   habitat:"Larves dans un fourreau de sable ou de brindilles au fond des rivières.", robe:"Larve crème dans un étui brun ; adulte brun à ailes en toit.",
   imitation:"Nymphes casquées, mouches sèches."},
  {id:"grenouille", nom:"Grenouille verte", sci:"Pelophylax kl. esculentus", wiki:"Grenouille_verte", milieu:"douce", groupe:"Amphibien", roles:["proie"], taille:"6–12 cm",
   habitat:"Bords d'étangs, herbiers et nénuphars, très active en été.", robe:"Vert vif tacheté de noir, ligne claire sur le dos, ventre blanc.",
   imitation:"Leurres grenouille de surface (frog) dans les herbiers."},
  {id:"ver-terre", nom:"Ver de terre", sci:"Lumbricus terrestris", wiki:"Lombric_commun", milieu:"douce", groupe:"Ver", roles:["proie"], taille:"9–30 cm",
   habitat:"Emporté par les crues et le ruissellement dans les rivières.", robe:"Rose-brun, anneau clair (clitellum).",
   imitation:"Vers souples, pêche au toc."},
  // ---- Nouvelle-Calédonie ----
  {id:"nc-poulpe", zone:"nc", nom:"Poulpe (zourite)", sci:"Octopus cyanea", wiki:"Octopus_cyanea", milieu:"lagon", groupe:"Céphalopode", roles:["proie"], taille:"30–80 cm (bras compris)",
   habitat:"Platiers et récifs, chasse de jour à marée basse.", robe:"Brun moucheté, tache sombre (ocelle) sous l'œil, change de couleur en permanence.",
   imitation:"Leurres souples à tentacules, madaï."},
  {id:"nc-calmar", zone:"nc", nom:"Calmar du récif", sci:"Sepioteuthis lessoniana", wiki:"Sepioteuthis_lessoniana", milieu:"lagon", groupe:"Céphalopode", roles:["proie"], taille:"15–35 cm (manteau)",
   habitat:"Herbiers et bord des récifs, en surface la nuit.", robe:"Translucide à reflets verts et pourpres, nageoire sur toute la longueur du corps.",
   imitation:"Turluttes, leurres à jupe."},
  {id:"nc-langouste", zone:"nc", nom:"Langouste", sci:"Panulirus versicolor", wiki:"Panulirus_versicolor", milieu:"lagon", groupe:"Crustacé", roles:["proie"], taille:"20–40 cm",
   habitat:"Trous et surplombs du récif, sort la nuit.", robe:"Bleu-vert à bandes blanches et noires, longues antennes roses.",
   imitation:"Peu imitée au leurre ; proie naturelle des grosses carangues."},
  {id:"nc-crabe", zone:"nc", nom:"Crabe de palétuvier", sci:"Scylla serrata", wiki:"Scylla_serrata", milieu:"lagon", groupe:"Crustacé", roles:["proie"], taille:"10–20 cm (carapace)",
   habitat:"Mangroves et vasières, terriers dans la vase.", robe:"Vert olive à brun, grosses pinces lisses.",
   imitation:"Leurres crabe près des racines de palétuviers."},
  {id:"nc-crevette", zone:"nc", nom:"Crevette pénéide", sci:"Penaeus monodon", wiki:"Penaeus_monodon", milieu:"lagon", groupe:"Crustacé", roles:["proie"], taille:"8–25 cm",
   habitat:"Mangroves, estuaires et fonds vaseux du lagon, active la nuit.", robe:"Translucide grisâtre à bandes sombres transversales.",
   imitation:"Leurres souples crevette, poissons nageurs lents."},
  {id:"nc-oursin", zone:"nc", nom:"Oursin du platier", sci:"Echinometra mathaei", wiki:"Echinometra_mathaei", milieu:"lagon", groupe:"Échinoderme", roles:["proie"], taille:"5–8 cm",
   habitat:"Trous du platier et du récif peu profond.", robe:"Piquants courts violets à verts, base claire.",
   imitation:"Non imitable au leurre : nourriture du bec de cane."}
);

// Proies non-poissons ajoutées au régime des prédateurs
window.MANGE_PLUS={
  bar:["crabe-vert","etrille","crevette-grise","bouquet","seiche","calmar","nereis","arenicole"],
  lieu:["calmar","bouquet"], maquereau:["crevette-grise"], thon:["calmar"], bonite:["calmar"], seriole:["calmar","seiche","poulpe"],
  dorade:["moule","crabe-vert","etrille","crevette-grise","nereis","arenicole"],
  brochet:["ecrevisse","grenouille"], sandre:["ecrevisse"], perche:["ecrevisse","gammare","ephemere"], blackbass:["ecrevisse","grenouille"],
  silure:["ecrevisse","grenouille"], truite:["gammare","ephemere","trichoptere","ver-terre"], chevesne:["ecrevisse","ephemere","trichoptere","ver-terre"],
  "nc-gt":["nc-poulpe","nc-langouste","nc-crabe"], "nc-carangue-bleue":["nc-crevette"], "nc-saumonee":["nc-calmar","nc-crevette"],
  "nc-bec-de-cane":["nc-crabe","nc-crevette","nc-oursin"], "nc-barracuda":["nc-calmar"], "nc-thazard":["nc-calmar"], "nc-lutjan-mangrove":["nc-crabe","nc-crevette"],
  "nc-dent-de-chien":["nc-calmar"], "nc-thon-jaune":["nc-calmar"], "nc-wahoo":["nc-calmar"], "nc-mahi":["nc-calmar"], "nc-marlin":["nc-calmar"], "nc-listao":["nc-crevette"]
};

// Détails supplémentaires. maille = taille minimale indicative (France), à vérifier dans l'arrêté de ton secteur.
window.ESPECES_DETAILS={
  // France eau douce
  brochet:{comportement:"Chasseur à l'affût, immobile dans les herbiers puis attaque éclair. Plus actif par temps couvert et eau légèrement teintée.",saison:"Meilleur au printemps après l'ouverture et en automne ; fermé de fin janvier à fin avril en 2e catégorie.",profondeur:"Bordures et herbiers de 0,5 à 4 m ; plus profond en plein été et en hiver.",techniques:"Gros leurres souples, jerkbaits, spinnerbaits, cuillers ; bas de ligne acier ou fluorocarbone épais obligatoire.",maille:"60 cm (2 par jour en 2e catégorie, selon département)"},
  sandre:{comportement:"Chasse en groupe, surtout à l'aube, au crépuscule et la nuit ; craint la lumière vive.",saison:"Ouverture et automne-hiver très productifs ; réglementation variable selon le secteur.",profondeur:"Près du fond, souvent 3 à 10 m, sur les cassures et les zones dures.",techniques:"Leurres souples fins en linéaire lent ou en verticale, jigs, poissons nageurs plongeants la nuit.",maille:"50 cm sur certains secteurs (ex. Vilaine), selon département"},
  perche:{comportement:"Chasse en bancs, souvent en chasses de surface spectaculaires sur les alevins.",saison:"Toute l'année ; pic de fin d'été à l'automne.",profondeur:"Structures immergées, 1 à 8 m ; plus profond en hiver.",techniques:"Petits leurres souples, cuillers tournantes, micro-jigs, drop-shot.",maille:"Pas de taille nationale ; parfois fixée localement"},
  blackbass:{comportement:"Territorial, attaque par réflexe ou agressivité près des obstacles.",saison:"Ouverture mi-juin à l'automne ; très actif quand l'eau dépasse 18 °C.",profondeur:"Bordures, herbiers et bois noyés, 0,5 à 5 m.",techniques:"Leurres de surface, grenouilles, texas, spinnerbaits, crankbaits.",maille:"40 cm (2e catégorie, selon département)"},
  silure:{comportement:"Opportuniste nocturne, détecte vibrations et odeurs ; peut chasser en surface.",saison:"Printemps à automne, surtout eau chaude (plus de 15 °C).",profondeur:"Fosses et bordures encombrées, 2 à 15 m.",techniques:"Gros souples, vibrations au fond, clonk, matériel très costaud.",maille:"Pas de taille minimale"},
  truite:{comportement:"Postée face au courant derrière un obstacle, chasse à vue les proies dérivantes.",saison:"Ouverture en mars à mi-septembre (1re catégorie) ; éclosions de mai-juin.",profondeur:"Courants, têtes de radier, sous-berges, 0,3 à 2 m.",techniques:"Petites cuillers tournantes, poissons nageurs 3 à 7 cm, mouche.",maille:"23 cm minimum national, souvent plus selon département"},
  chevesne:{comportement:"Méfiant, en bancs sous les arbres, gobe tout ce qui tombe à l'eau.",saison:"Printemps à automne, surtout l'été.",profondeur:"Surface et mi-eau sous les branches.",techniques:"Petits leurres de surface, insectes artificiels, cuillers.",maille:"Pas de taille minimale"},
  // France mer
  bar:{comportement:"Chasse dans l'écume, les courants et les zones de remous, surtout à l'aube, au crépuscule et la nuit.",saison:"Printemps à fin d'automne à la côte ; regroupements de reproduction en hiver au large.",profondeur:"De quelques dizaines de cm (écume) à 20 m.",techniques:"Leurres de surface (stickbaits, poppers), poissons nageurs, souples type lançon.",maille:"42 cm ; quotas journaliers et périodes de pêche-relâche selon zone (nord/sud du 48e parallèle)"},
  lieu:{comportement:"Monte chasser en pleine eau au-dessus des roches et des épaves, surtout aux étales et au coucher du soleil.",saison:"Printemps-automne à la côte ; capture interdite du 1er janvier au 30 avril en 2026 (Manche-Atlantique, à vérifier chaque année).",profondeur:"5 à 60 m au-dessus des structures.",techniques:"Souples en linéaire lent, jigs, traîne lente.",maille:"30 cm ; 2 par pêcheur et par jour en 2026"},
  maquereau:{comportement:"Gros bancs très mobiles qui chassent en surface (chasses d'oiseaux).",saison:"Mai à octobre à la côte.",profondeur:"Surface à 30 m.",techniques:"Mitraillettes, petits casting jigs, cuillers.",maille:"20 cm"},
  thon:{comportement:"Grands chasseurs en bancs, chasses de surface sur sardines et anchois.",saison:"Été-automne dans le golfe de Gascogne.",profondeur:"Surface à 100 m.",techniques:"Stickbaits, poppers, jigs ; matériel lourd.",maille:"Pêche de loisir très encadrée : autorisation, déclaration, marquage, quotas. Vérifie la réglementation de l'année."},
  bonite:{comportement:"Bancs rapides qui chassent en surface.",saison:"Été-automne (Méditerranée, sud Gascogne).",profondeur:"Surface à 30 m.",techniques:"Casting jigs lancés et ramenés vite.",maille:"Vérifie la réglementation locale"},
  seriole:{comportement:"Patrouille en groupes autour des épaves et des tombants.",saison:"Été-automne surtout en Méditerranée.",profondeur:"10 à 80 m.",techniques:"Jigs lourds, gros stickbaits, vif.",maille:"Vérifie la réglementation locale"},
  dorade:{comportement:"Fouille le fond, casse les coquillages avec ses dents broyeuses.",saison:"Printemps-été à la côte, remonte dans les estuaires.",profondeur:"1 à 30 m sur fonds mixtes.",techniques:"Leurres crabe, petits souples au fond, appâts naturels.",maille:"23 cm (Atlantique, à vérifier)"},
  // France proies poissons
  gardon:{saison:"Toute l'année, frai en avril-mai.",comportement:"Bancs en pleine eau et bordures.",imitation:"Souples et poissons nageurs argentés à nageoires rouges."},
  ablette:{saison:"Surtout printemps-été.",comportement:"Gros bancs en surface, fuient en sautant.",imitation:"Leurres fins très brillants, cuillers."},
  rotengle:{saison:"Printemps-été dans les herbiers.",comportement:"Bancs près des herbiers en surface.",imitation:"Leurres dorés à nageoires rouges."},
  goujon:{saison:"Toute l'année.",comportement:"Au fond, en petits groupes sur le sable.",imitation:"Souples beige-brun tachetés, au ras du fond."},
  vairon:{saison:"Toute l'année en eau vive.",comportement:"Bancs près des bords, fuient au moindre mouvement.",imitation:"Petits poissons nageurs 3–5 cm, cuillers tournantes."},
  breme:{saison:"Toute l'année.",comportement:"Bancs au fond en eau lente.",imitation:"Gros souples hauts et plats, couleurs bronze."},
  carassin:{saison:"Printemps-été.",comportement:"Fouille la vase en eau calme.",imitation:"Souples dorés trapus."},
  chabot:{saison:"Toute l'année.",comportement:"Immobile sous les pierres, déplacements brefs.",imitation:"Souples courts à grosse tête, au fond."},
  loche:{saison:"Toute l'année.",comportement:"Nocturne, sous les graviers.",imitation:"Petits souples allongés bruns."},
  hotu:{saison:"Printemps (frai sur les graviers).",comportement:"Bancs au fond dans le courant.",imitation:"Souples argentés de 10–15 cm."},
  gremille:{saison:"Toute l'année.",comportement:"Petits groupes au fond.",imitation:"Petits souples tachetés au fond."},
  perchette:{saison:"Été-automne (jeunes de l'année).",comportement:"Bancs serrés près des structures.",imitation:"Souples et nageurs à rayures verticales, nageoires orange."},
  sardine:{saison:"Printemps-automne à la côte.",comportement:"Bancs denses en pleine eau, très chassés.",imitation:"Stickbaits et souples argent à dos bleu-vert."},
  anchois:{saison:"Printemps-été.",comportement:"Bancs très serrés, en boule face aux prédateurs.",imitation:"Petits jigs et souples fins translucides."},
  sprat:{saison:"Hiver-printemps dans les estuaires.",comportement:"Bancs côtiers.",imitation:"Petits leurres argentés."},
  lancon:{saison:"Printemps-automne près des plages.",comportement:"S'enfouit dans le sable, sort en bancs au courant.",imitation:"Souples longs et fins (type lançon), slugs."},
  chinchard:{saison:"Été-automne.",comportement:"Bancs près des roches et des ports, souvent la nuit.",imitation:"Nageurs et souples argent à dos vert."},
  atherine:{saison:"Printemps-été dans les ports.",comportement:"Bancs en surface.",imitation:"Petits leurres translucides à bande argentée."},
  orphie:{saison:"Printemps (avril-mai) à la côte.",comportement:"En surface, saute hors de l'eau.",imitation:"Leurres longs et fins de surface."},
  tacaud:{saison:"Toute l'année sur les épaves.",comportement:"Bancs au-dessus des roches.",imitation:"Souples cuivrés à bandes sombres."},
  mulet:{saison:"Printemps-automne dans les ports et estuaires.",comportement:"Bancs en surface, broutent les algues.",imitation:"Nageurs et stickbaits gris argenté."},
  gobie:{saison:"Toute l'année.",comportement:"Posé au fond, déplacements par bonds.",imitation:"Petits souples bruns au ras du fond."},
  // Nouvelle-Calédonie prédateurs
  "nc-gt":{comportement:"Patrouille seule ou en petits groupes, attaque violente en surface.",saison:"Toute l'année ; marées montantes et changements de lumière.",profondeur:"Surface à 50 m.",techniques:"Poppers et stickbaits lourds, matériel très puissant (PE 6 à 10)."},
  "nc-carangue-bleue":{comportement:"Chasse en groupes le long des récifs.",saison:"Toute l'année.",profondeur:"Surface à 30 m.",techniques:"Stickbaits, petits poppers, jigs."},
  "nc-saumonee":{comportement:"Chasse à l'affût depuis les patates de corail.",saison:"Toute l'année (attention aux périodes de protection de la reproduction).",profondeur:"5 à 40 m.",techniques:"Poissons nageurs plongeants, jigs."},
  "nc-bec-de-cane":{comportement:"Fouille le sable et les herbiers.",saison:"Toute l'année.",profondeur:"2 à 30 m.",techniques:"Leurres de fond, appâts."},
  "nc-barracuda":{comportement:"Rôde en bordure, attaque à grande vitesse.",saison:"Toute l'année.",profondeur:"Surface à 20 m.",techniques:"Leurres longs, traîne, bas de ligne acier."},
  "nc-thazard":{comportement:"Chasseur rapide des passes et des bordures.",saison:"Pic de la saison chaude.",profondeur:"Surface à 30 m.",techniques:"Traîne rapide, casting jigs, bas de ligne acier."},
  "nc-lutjan-mangrove":{comportement:"Chasse le long des racines, surtout à marée montante.",saison:"Toute l'année.",profondeur:"Mangrove peu profonde (jeunes) à 50 m (adultes).",techniques:"Souples et nageurs près des obstacles."},
  "nc-dent-de-chien":{comportement:"Chasse le long des tombants dans le courant.",saison:"Toute l'année.",profondeur:"10 à 100 m.",techniques:"Jigs lourds, stickbaits plongeants."},
  "nc-thon-jaune":{comportement:"Bancs sous les oiseaux et autour des DCP.",saison:"Surtout saison chaude.",profondeur:"Surface à 100 m.",techniques:"Stickbaits, poppers, traîne."},
  "nc-wahoo":{comportement:"Solitaire, extrêmement rapide.",saison:"Saison fraîche et intersaisons.",profondeur:"Surface à 20 m.",techniques:"Traîne rapide 12–18 nœuds, bas de ligne acier."},
  "nc-mahi":{comportement:"Suit les objets flottants, en couple ou en groupe.",saison:"Saison chaude.",profondeur:"Surface.",techniques:"Leurres à jupe, stickbaits colorés."},
  "nc-marlin":{comportement:"Grand chasseur du large, suit les bancs de thons.",saison:"Saison chaude (novembre à avril).",profondeur:"Surface à 200 m.",techniques:"Gros leurres à jupe en traîne."},
  "nc-listao":{comportement:"Gros bancs en surface.",saison:"Toute l'année au large.",profondeur:"Surface à 50 m.",techniques:"Petits jigs, plumes en traîne.",imitation:"Gros leurres à jupe et stickbaits bleu-argent rayés."},
  // NC proies
  "nc-sardine":{saison:"Toute l'année dans les baies.",comportement:"Bancs denses en surface.",imitation:"Petits stickbaits et souples argent."},
  "nc-anchois":{saison:"Toute l'année.",comportement:"Bancs en boule.",imitation:"Petits jigs, souples translucides."},
  "nc-selar":{saison:"Toute l'année, surtout la nuit.",comportement:"Bancs près de la surface la nuit.",imitation:"Nageurs argent à dos bleu-vert."},
  "nc-mulet":{saison:"Toute l'année.",comportement:"Bancs sur les platiers.",imitation:"Stickbaits gris argenté."},
  "nc-balaou":{saison:"Toute l'année.",comportement:"En surface, saute pour fuir.",imitation:"Leurres longs et fins de surface."},
  "nc-volant":{saison:"Toute l'année au large.",comportement:"Plane au-dessus de l'eau pour fuir.",imitation:"Leurres à jupe bleu-argent, stickbaits volants."},
  "nc-fusilier":{saison:"Toute l'année.",comportement:"Gros bancs le long des tombants.",imitation:"Leurres bleu et jaune."},
  "nc-rouget":{saison:"Toute l'année.",comportement:"Bancs sur le sable, fouille avec ses barbillons.",imitation:"Souples blancs à bande jaune au fond."}
};
