// Référence « Proies et prédateurs » (France). Données de synthèse, modifiables ici.
// milieu : "mer" ou "douce". roles : "predateur" et/ou "proie".
// mange : identifiants des poissons-proies. autres : nourriture hors poissons.
window.ESPECES = [
  // ===== Eau douce : prédateurs =====
  {id:"brochet", nom:"Brochet", sci:"Esox lucius", wiki:"Grand_brochet", milieu:"douce", roles:["predateur"], taille:"50–100 cm (jusqu'à 130 cm)",
   habitat:"Eaux calmes, bordures d'herbiers, bras morts, lacs.",
   mange:["gardon","rotengle","ablette","perchette","breme","carassin","chevesne","goujon"],
   autres:"Écrevisses, grenouilles, canetons, petits rongeurs ; cannibale.",
   conseil:"Avale des proies jusqu'à la moitié de sa taille : leurres de 10 à 25 cm."},
  {id:"sandre", nom:"Sandre", sci:"Sander lucioperca", wiki:"Sandre", milieu:"douce", roles:["predateur"], taille:"40–80 cm (jusqu'à 100 cm)",
   habitat:"Fonds durs, eaux un peu troubles, grands fleuves, lacs et canaux.",
   mange:["ablette","goujon","gardon","perchette","gremille"],
   autres:"Écrevisses.",
   conseil:"Gosier étroit : proies fines et allongées, leurres de 7 à 14 cm."},
  {id:"perche", nom:"Perche", sci:"Perca fluviatilis", wiki:"Perche_commune", milieu:"douce", roles:["predateur"], taille:"20–30 cm (jusqu'à 45 cm)",
   habitat:"Lacs, rivières lentes, structures immergées ; chasse en bandes.",
   mange:["ablette","gardon","vairon","perchette","goujon","gremille"],
   autres:"Écrevisses, larves, vers, crustacés ; cannibale.",
   conseil:"Proies de 3 à 8 cm : petits leurres, cuillers, finesse."},
  {id:"blackbass", nom:"Black-bass", sci:"Micropterus salmoides", wiki:"Achigan_à_grande_bouche", milieu:"douce", roles:["predateur"], taille:"30–50 cm",
   habitat:"Eaux chaudes et calmes, herbiers, bois morts, étangs et lacs.",
   mange:["gardon","ablette","perchette","vairon","rotengle"],
   autres:"Écrevisses, grenouilles, gros insectes.",
   conseil:"Très opportuniste en surface comme au fond."},
  {id:"silure", nom:"Silure", sci:"Silurus glanis", wiki:"Silure_glane", milieu:"douce", roles:["predateur"], taille:"100–200 cm (plus de 2,5 m)",
   habitat:"Grands fleuves et lacs, fosses, bordures encombrées.",
   mange:["breme","carassin","rotengle","chevesne","gardon","hotu"],
   autres:"Écrevisses, amphibiens, oiseaux d'eau, mollusques (corbicules).",
   conseil:"Gros leurres souples et vibrants, souvent près du fond."},
  {id:"truite", nom:"Truite fario", sci:"Salmo trutta", wiki:"Truite_fario", milieu:"douce", roles:["predateur"], taille:"20–40 cm (jusqu'à 70 cm)",
   habitat:"Eaux vives, fraîches et oxygénées, torrents et rivières.",
   mange:["vairon","chabot","loche","goujon"],
   autres:"Insectes aquatiques et terrestres, gammares ; les grosses truites deviennent piscivores.",
   conseil:"Imitations de vairon de 3 à 7 cm, cuillers tournantes."},
  {id:"chevesne", nom:"Chevesne", sci:"Squalius cephalus", wiki:"Chevesne", milieu:"douce", roles:["predateur","proie"], taille:"30–50 cm",
   habitat:"Rivières courantes, sous les arbres en bordure.",
   mange:["vairon","ablette","goujon"],
   autres:"Insectes, fruits tombés, écrevisses, graines.",
   robe:"Dos gris-vert sombre, flancs argentés à reflets dorés, écailles bordées de noir, nageoires ventrales orangées.",
   conseil:"Omnivore : petits poissons nageurs, insectes de surface."},
  // ===== Eau douce : poissons fourrage =====
  {id:"gardon", nom:"Gardon", sci:"Rutilus rutilus", wiki:"Gardon", milieu:"douce", roles:["proie"], taille:"10–25 cm",
   habitat:"Eaux calmes ou lentes, en bancs.", robe:"Dos vert-bleuté, flancs très argentés, nageoires rouge orangé, œil rouge."},
  {id:"ablette", nom:"Ablette", sci:"Alburnus alburnus", wiki:"Ablette", milieu:"douce", roles:["proie"], taille:"10–15 cm",
   habitat:"Pleine eau et surface, gros bancs.", robe:"Corps fin très brillant, argent miroir, dos vert-bleu, ventre blanc."},
  {id:"rotengle", nom:"Rotengle", sci:"Scardinius erythrophthalmus", wiki:"Rotengle", milieu:"douce", roles:["proie"], taille:"15–30 cm",
   habitat:"Eaux calmes riches en herbiers.", robe:"Flancs dorés à bronze, nageoires rouge vif, dos brun-vert."},
  {id:"goujon", nom:"Goujon", sci:"Gobio gobio", wiki:"Goujon", milieu:"douce", roles:["proie"], taille:"8–15 cm",
   habitat:"Fond de sable ou de gravier, en petits groupes.", robe:"Brun-gris tacheté de sombre le long du flanc, ventre clair, 2 barbillons."},
  {id:"vairon", nom:"Vairon", sci:"Phoxinus phoxinus", wiki:"Vairon", milieu:"douce", roles:["proie"], taille:"5–10 cm",
   habitat:"Eaux vives et fraîches, en bancs près des bords.", robe:"Vert olive marbré de taches sombres, flanc doré, ventre rouge chez le mâle au printemps."},
  {id:"breme", nom:"Brème (jeune)", sci:"Abramis brama", wiki:"Brème_commune", milieu:"douce", roles:["proie"], taille:"Juvéniles 10–25 cm (adulte 30–60 cm)",
   habitat:"Eaux lentes et profondes, fonds vaseux.", robe:"Corps haut et plat, argenté chez le jeune, bronze chez l'adulte."},
  {id:"carassin", nom:"Carassin", sci:"Carassius carassius", wiki:"Carassin_commun", milieu:"douce", roles:["proie"], taille:"15–30 cm",
   habitat:"Étangs et eaux calmes envasées.", robe:"Bronze doré, corps haut, sans barbillons."},
  {id:"chabot", nom:"Chabot", sci:"Cottus gobio", wiki:"Chabot_commun", milieu:"douce", roles:["proie"], taille:"8–15 cm",
   habitat:"Sous les pierres des rivières fraîches.", robe:"Brun marbré, grosse tête aplatie, larges nageoires pectorales."},
  {id:"loche", nom:"Loche franche", sci:"Barbatula barbatula", wiki:"Loche_franche", milieu:"douce", roles:["proie"], taille:"8–12 cm",
   habitat:"Fond de graviers en eau courante.", robe:"Corps allongé brun-jaune marbré, 6 barbillons."},
  {id:"hotu", nom:"Hotu", sci:"Chondrostoma nasus", wiki:"Hotu", milieu:"douce", roles:["proie"], taille:"25–40 cm",
   habitat:"Grandes rivières courantes, fonds de graviers, en bancs.", robe:"Argenté, dos gris-vert, nageoires inférieures rougeâtres, bouche sous le museau."},
  {id:"gremille", nom:"Grémille", sci:"Gymnocephalus cernua", wiki:"Grémille", milieu:"douce", roles:["proie"], taille:"10–15 cm",
   habitat:"Fonds de fleuves et de lacs.", robe:"Brun-jaune tacheté de noir, dorsale épineuse ponctuée."},
  {id:"perchette", nom:"Perchette", sci:"Perca fluviatilis", wiki:"Perche_commune", milieu:"douce", roles:["proie"], taille:"5–15 cm",
   habitat:"Bordures, structures, en bancs.", robe:"Vert-jaune à 5–7 bandes verticales sombres, nageoires ventrales orange vif."},

  // ===== Mer : prédateurs =====
  {id:"bar", nom:"Bar (loup)", sci:"Dicentrarchus labrax", wiki:"Bar_commun", milieu:"mer", roles:["predateur"], taille:"40–60 cm (jusqu'à 1 m)",
   habitat:"Côtes, estuaires, zones d'écume, roches et plages ; Atlantique, Manche, Méditerranée.",
   mange:["sardine","anchois","sprat","lancon","atherine","chinchard","mulet","gobie","tacaud"],
   autres:"Crabes, crevettes, seiches et calmars, vers polychètes.",
   conseil:"Leurres de 9 à 15 cm imitant lançon, sardine ou mulet."},
  {id:"lieu", nom:"Lieu jaune", sci:"Pollachius pollachius", wiki:"Lieu_jaune", milieu:"mer", roles:["predateur"], taille:"40–80 cm (jusqu'à 1,3 m)",
   habitat:"Roches, laminaires, épaves, de 1 à 100 m ; Atlantique et Manche.",
   mange:["lancon","sprat","tacaud","chinchard","sardine","atherine"],
   autres:"Calmars, crevettes.",
   conseil:"Souples de 10 à 18 cm type lançon, près des épaves."},
  {id:"maquereau", nom:"Maquereau", sci:"Scomber scombrus", wiki:"Maquereau_commun", milieu:"mer", roles:["predateur","proie"], taille:"25–40 cm",
   habitat:"Pleine eau côtière, en bancs ; présent en été près des côtes.",
   mange:["sprat","anchois","sardine","lancon","atherine"],
   autres:"Zooplancton : copépodes, krill, larves.",
   robe:"Dos vert-bleu zébré de bandes noires ondulées, ventre blanc nacré.",
   conseil:"Petits leurres brillants de 3 à 8 cm, mitraillettes."},
  {id:"thon", nom:"Thon rouge", sci:"Thunnus thynnus", wiki:"Thon_rouge_de_l'Atlantique", milieu:"mer", roles:["predateur"], taille:"100–250 cm",
   habitat:"Large ; golfe de Gascogne en été-automne, Méditerranée.",
   mange:["sardine","anchois","maquereau","chinchard","sprat","orphie"],
   autres:"Calmars, crustacés pélagiques.",
   conseil:"Stickbaits et poppers de 15 à 25 cm, sardine ou maquereau."},
  {id:"bonite", nom:"Bonite à dos rayé", sci:"Sarda sarda", wiki:"Bonite_à_dos_rayé", milieu:"mer", roles:["predateur"], taille:"40–70 cm",
   habitat:"Pleine eau, chasses en surface ; Méditerranée et Atlantique sud.",
   mange:["sardine","anchois","atherine","sprat","maquereau"],
   autres:"Calmars.",
   conseil:"Jigs et casting jigs de 20 à 40 g, lancés vite."},
  {id:"seriole", nom:"Sériole", sci:"Seriola dumerili", wiki:"Sériole_couronnée", milieu:"mer", roles:["predateur"], taille:"60–120 cm (jusqu'à 1,9 m)",
   habitat:"Tombants, épaves, hauts-fonds ; Méditerranée surtout.",
   mange:["chinchard","maquereau","sardine","mulet","orphie"],
   autres:"Calmars, seiches.",
   conseil:"Jigs lourds et gros stickbaits."},
  {id:"dorade", nom:"Dorade royale", sci:"Sparus aurata", wiki:"Dorade_royale", milieu:"mer", roles:["predateur"], taille:"30–50 cm (jusqu'à 70 cm)",
   habitat:"Fonds sableux et rocheux côtiers, lagunes, estuaires.",
   mange:[],
   autres:"Surtout coquillages et crustacés : moules, crabes, bernard-l'ermite, crevettes, oursins, vers. Peu de poissons.",
   conseil:"Peu réceptive aux leurres imitant des poissons : imitations de crabe et petits leurres de fond."},
  // ===== Mer : poissons fourrage =====
  {id:"sardine", nom:"Sardine", sci:"Sardina pilchardus", wiki:"Sardine_commune", milieu:"mer", roles:["proie"], taille:"15–25 cm",
   habitat:"Pleine eau côtière, gros bancs.", robe:"Dos bleu-vert, flancs argentés, ligne de taches sombres sur le haut du flanc."},
  {id:"anchois", nom:"Anchois", sci:"Engraulis encrasicolus", wiki:"Anchois_commun", milieu:"mer", roles:["proie"], taille:"10–15 cm",
   habitat:"Pleine eau, bancs très denses.", robe:"Corps fin semi-translucide, dos bleu-vert, bande latérale argentée."},
  {id:"sprat", nom:"Sprat", sci:"Sprattus sprattus", wiki:"Sprat", milieu:"mer", roles:["proie"], taille:"8–14 cm",
   habitat:"Côtes et estuaires, en bancs.", robe:"Argenté, dos bleu-vert, ventre caréné."},
  {id:"lancon", nom:"Lançon (équille)", sci:"Ammodytes tobianus", wiki:"Lançon_équille", milieu:"mer", roles:["proie"], taille:"10–20 cm",
   habitat:"Fonds de sable où il s'enfouit, en bancs près des plages.", robe:"Très effilé, argent brillant, dos vert-bleu."},
  {id:"chinchard", nom:"Chinchard", sci:"Trachurus trachurus", wiki:"Chinchard_commun", milieu:"mer", roles:["proie"], taille:"Juvéniles 10–25 cm",
   habitat:"Pleine eau, bancs, près des roches et des ports.", robe:"Dos gris-vert, flancs argentés, ligne latérale à scutelles, tache noire sur l'opercule."},
  {id:"atherine", nom:"Athérine (prêtre)", sci:"Atherina presbyter", wiki:"Atherina_presbyter", milieu:"mer", roles:["proie"], taille:"7–15 cm",
   habitat:"Ports, plages, estuaires, en bancs.", robe:"Translucide, large bande argentée brillante sur le flanc."},
  {id:"orphie", nom:"Orphie", sci:"Belone belone", wiki:"Orphie", milieu:"mer", roles:["proie"], taille:"40–80 cm",
   habitat:"Surface, côtes au printemps.", robe:"Très effilée, dos vert-bleu, flancs argentés, long bec, arêtes vertes."},
  {id:"tacaud", nom:"Tacaud", sci:"Trisopterus luscus", wiki:"Tacaud_commun", milieu:"mer", roles:["proie"], taille:"15–30 cm",
   habitat:"Roches, épaves, en bancs.", robe:"Cuivré à 4–5 bandes verticales sombres, petit barbillon au menton."},
  {id:"mulet", nom:"Mulet (jeune)", sci:"Chelon labrosus", wiki:"Mulet_lippu", milieu:"mer", roles:["proie"], taille:"Juvéniles 5–20 cm",
   habitat:"Ports, estuaires, surface, en bancs.", robe:"Gris argenté, fines lignes sombres longitudinales."},
  {id:"gobie", nom:"Gobie", sci:"Gobius paganellus", wiki:"Gobie_paganel", milieu:"mer", roles:["proie"], taille:"8–12 cm",
   habitat:"Fonds rocheux et flaques de l'estran.", robe:"Brun marbré, bande claire au bord de la première dorsale."}
];
