// Fiches filaments pour la Creality K2 Plus (buse 0,4 mm, plateau ≤ 120 °C, enceinte chauffée active ≤ 60 °C, alimentation 1200 W).
// Températures : valeurs de départ (profils Creality / guides publics). Le profil Creality Print de ta bobine reste la référence.
// watts : puissance moyenne estimée pendant l'impression. src "publié" = plage publiée pour la K2 Plus, "estimé" = estimation à vérifier au wattmètre.
// Notes de 1 (faible) à 5 (excellent).
window.FILAMENTS_DATA = [
  {id:"PLA", nom:"PLA", densite:1.24, buse:"210–220 °C", plateau:"55–60 °C", chambre:"Non : enceinte 30–35 °C, couvercle entrouvert si chaleur", chauffe:false,
   watts:175, wattsSrc:"publié (150–200 W)", hdt:"≈ 55–60 °C", prixKg:"15–25 €",
   notes:{uv:1,meca:3,choc:2,chaleur:1,eau:2,facilite:5,flex:1},
   plus:["Le plus facile à imprimer, très précis","Rigide, beaux détails, large choix de couleurs","Peu d'odeur"],
   moins:["Se déforme dès 55–60 °C (voiture au soleil, coffre)","Fragile aux chocs, cassant","Se dégrade lentement dans l'eau et au soleil"],
   leurres:"Prototypes et gabarits uniquement. Pas pour un leurre qui pêche."},
  {id:"PETG", nom:"PETG", densite:1.27, buse:"240–250 °C", plateau:"70–80 °C", chambre:"Non : enceinte 30–35 °C", chauffe:false,
   watts:210, wattsSrc:"estimé (plateau 80 °C, sans chauffe d'enceinte)", hdt:"≈ 70–80 °C", prixKg:"18–28 €",
   notes:{uv:3,meca:4,choc:4,chaleur:2,eau:5,facilite:4,flex:2},
   plus:["Très bonne tenue à l'eau et au sel","Résistant aux chocs, peu cassant","Facile, pas besoin d'enceinte chauffée","Bonne adhérence des résines et peintures"],
   moins:["Ramollit vers 70–80 °C","Fils et bavures (stringing)","Moins rigide que l'ASA, rayable"],
   leurres:"Bon compromis pour des corps de leurres, surtout sous résine."},
  {id:"ABS", nom:"ABS", densite:1.04, buse:"250–260 °C", plateau:"90–100 °C", chambre:"Oui : enceinte chauffée 50–60 °C", chauffe:true,
   watts:350, wattsSrc:"publié (300–400 W avec enceinte chauffée)", hdt:"≈ 90–100 °C", prixKg:"18–28 €",
   notes:{uv:2,meca:3,choc:4,chaleur:4,eau:4,facilite:2,flex:2},
   plus:["Léger (densité 1,04) : leurres plus flottants","Tient la chaleur","Lissage à l'acétone possible","Se ponce et se colle bien"],
   moins:["Jaunit et devient cassant au soleil","Gondole (warping) sans enceinte chaude","Odeur et émissions : aérer"],
   leurres:"Correct sous résine ou peinture qui le protège des UV ; préférer l'ASA."},
  {id:"ASA", nom:"ASA", densite:1.07, buse:"250–260 °C", plateau:"90–100 °C", chambre:"Oui : enceinte chauffée 50–60 °C", chauffe:true,
   watts:350, wattsSrc:"publié (300–400 W avec enceinte chauffée)", hdt:"≈ 90–100 °C", prixKg:"22–35 €",
   notes:{uv:5,meca:4,choc:4,chaleur:4,eau:5,facilite:3,flex:2},
   plus:["Excellente résistance aux UV, ne jaunit pas","Léger (densité 1,07) : flottabilité","Tient la chaleur et l'eau de mer","Lissage à l'acétone possible"],
   moins:["Enceinte chauffée nécessaire","Odeur et émissions : aérer","Un peu plus cher"],
   leurres:"Le meilleur choix pour des corps de leurres exposés au soleil et au sel."},
  {id:"TPU", nom:"TPU 95A", densite:1.21, buse:"220–230 °C", plateau:"35–45 °C", chambre:"Non : enceinte 30–35 °C", chauffe:false,
   watts:150, wattsSrc:"estimé (plateau tiède, impression lente)", hdt:"souple", prixKg:"25–40 €",
   notes:{uv:3,meca:3,choc:5,chaleur:2,eau:4,facilite:2,flex:5},
   plus:["Souple et élastique","Quasi incassable, résiste à l'abrasion","Bonne tenue à l'eau"],
   moins:["Impression lente","Fils et difficultés en multi-couleur (CFS déconseillé pour le TPU très souple)","Difficile à peindre"],
   leurres:"Queues souples, jupes, bavettes souples, pièces anti-choc."},
  {id:"PC", nom:"PC (polycarbonate)", densite:1.20, buse:"260–280 °C", plateau:"100–110 °C", chambre:"Oui : enceinte chauffée 60 °C (maximum)", chauffe:true,
   watts:400, wattsSrc:"estimé (plateau 110 °C + enceinte 60 °C)", hdt:"≈ 110–130 °C", prixKg:"30–45 €",
   notes:{uv:3,meca:5,choc:5,chaleur:5,eau:4,facilite:1,flex:2},
   plus:["Le plus résistant aux chocs","Tient de hautes températures","Rigide et tenace"],
   moins:["Difficile : gondole, demande l'enceinte au maximum","Absorbe l'humidité : sécher avant impression","Jaunit un peu aux UV sans protection"],
   leurres:"Leurres très exposés aux chocs (GT, rochers), bavettes rigides imprimées."},
  {id:"PA-CF", nom:"PA-CF (nylon carbone)", densite:1.15, buse:"270–300 °C", plateau:"80–100 °C", chambre:"Oui : enceinte chauffée 50–60 °C", chauffe:true,
   watts:380, wattsSrc:"estimé (buse chaude + enceinte chauffée)", hdt:"≈ 120–150 °C (sec)", prixKg:"40–70 €",
   notes:{uv:4,meca:5,choc:4,chaleur:5,eau:1,facilite:2,flex:1},
   plus:["Très rigide et résistant","Tient la chaleur","Aspect mat qui masque les couches","Buse trimétal de la K2 Plus compatible"],
   moins:["Absorbe l'eau et perd de sa rigidité une fois humide","Sécher avant impression et stocker au sec","Abrasif, cher"],
   leurres:"Déconseillé dans l'eau sans encapsulation totale ; bon pour outillage et pièces d'atelier."}
];
